set backspace=indent,eol,start
syntax enable
filetype plugin indent on
set background=dark
colorscheme solarized

if &background == "dark"
	let s:base03 = "NONE"
	let s:base02 = "NONE"
endif

set nu
set ruler
set hlsearch
set incsearch

" 1 tab == 4 spacesi
set shiftwidth=4
set tabstop=4

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines
"set showbreak=
