-- Combines the base colors of badger with the terminal colors of zenwritten dark. See:
-- - https://github.com/ccann/badger-theme/blob/master/badger-theme.el
-- - https://github.com/mcchrish/zenbones.nvim/blob/33672310aac6b823c88cf16d5d99472439111f9c/colors/zenwritten.vim
vim.opt.background = "dark"
vim.cmd("highlight clear")
vim.g.colors_name = "zenbadger"

local c = {
  bg = "#171717",
  panel = "#2f2f2f",
  line = "#1d1d1d",
  fg = "#bbbbbb",
  comment = "#7a7e7e",
  border = "#433f4f",
  subtle = "#756784",
  blue = "#8ac6f2",
  orange = "#ea9847",
  green = "#86b187",
  violet = "#bf93c3",
  constant = "#7d7395",
  salmon = "#f28b86",
  soft_violet = "#cdb0d0",
  soft_orange = "#efb579",
  sand = "#c7b299",
  cyan = "#65b8c1",
  red = "#e2434c",
  yellow = "#e0d063",
}

local groups = {
  -- Editor UI.
  Normal = { fg = c.fg, bg = c.bg },
  NormalFloat = { fg = c.fg, bg = c.line },
  FloatBorder = { fg = c.border, bg = c.line },
  FloatTitle = { fg = c.blue, bg = c.line },
  MiniClueDescGroup = { fg = c.violet },
  MiniPickBorderBusy = { fg = c.yellow, bg = c.line },
  MiniPickMatchCurrent = "Visual",
  MiniPickPrompt = "FloatTitle",
  Cursor = { fg = c.bg, bg = c.fg },
  CursorLine = { bg = c.line },
  CursorColumn = "CursorLine",
  ColorColumn = { bg = c.panel },
  CursorLineNr = { fg = c.fg, bold = true },
  LineNr = { fg = c.comment },
  SignColumn = { bg = c.bg },
  EndOfBuffer = "NonText",
  NonText = { fg = c.border },
  Whitespace = "NonText",
  WinSeparator = "NonText",
  Visual = { bg = c.panel },
  Search = { fg = c.bg, bg = c.yellow },
  IncSearch = { fg = c.bg, bg = c.orange },
  CurSearch = "IncSearch",
  MatchParen = { fg = c.yellow, bg = c.panel, bold = true },
  StatusLine = { fg = c.fg, bg = c.panel },
  StatusLineNC = { fg = c.subtle, bg = c.line },
  MsgArea = "lualine_c_command",
  WinBar = { fg = c.fg, bg = c.bg, bold = true },
  WinBarNC = { fg = c.subtle, bg = c.bg },
  TabLine = "StatusLineNC",
  TabLineFill = { bg = c.line },
  TabLineSel = { fg = c.blue, bg = c.panel, bold = true },
  Pmenu = "NormalFloat",
  PmenuSel = { fg = c.fg, bg = c.panel },
  PmenuSbar = { bg = c.border },
  PmenuThumb = { bg = c.comment },
  Folded = { fg = c.comment, bg = c.line },
  FoldColumn = { fg = c.comment, bg = c.bg },
  Directory = { fg = c.blue },
  Title = { fg = c.blue, bold = true },
  Question = { fg = c.green },
  MoreMsg = "Question",
  ErrorMsg = { fg = c.red },
  WarningMsg = { fg = c.yellow },
  ModeMsg = "Question",
  OkMsg = "Question",
  QuickFixLine = "Visual",
  SpellBad = { sp = c.red, undercurl = true },
  SpellCap = { sp = c.yellow, undercurl = true },
  SpellLocal = { sp = c.cyan, undercurl = true },
  SpellRare = { sp = c.violet, undercurl = true },

  -- Built-in syntax highlighting.
  Comment = { fg = c.comment },
  Constant = { fg = c.constant },
  String = { fg = c.green },
  Character = "String",
  Number = { fg = c.fg },
  Identifier = { fg = c.violet },
  Function = { fg = c.orange },
  Statement = { fg = c.blue },
  Keyword = "Statement",
  Operator = { fg = c.sand },
  PreProc = { fg = c.salmon },
  Type = { fg = c.sand },
  Special = { fg = c.salmon },
  Delimiter = { fg = c.fg },
  Underlined = { fg = c.blue, underline = true },
  Ignore = { fg = c.subtle },
  Error = { fg = c.red },
  Todo = { fg = c.yellow, bold = true },

  -- Tree-sitter and semantic highlighting.
  ["@constant.builtin"] = "Constant",
  ["@variable"] = { fg = c.soft_violet },
  ["@variable.parameter"] = "Identifier",
  ["@variable.member"] = "Identifier",
  ["@module"] = "Constant",
  ["@function.call"] = { fg = c.soft_orange, italic = true },
  ["@function.method"] = "@function.call",
  ["@constructor"] = "Type",
  ["@type.builtin"] = "Type",
  ["@property"] = "@variable.member",
  ["@lsp.type.parameter"] = "@variable",
  ["@lsp.type.method"] = "@function.method",

  ["@lsp.typemod.variable.declaration"] = "Identifier",
  ["@lsp.typemod.parameter.declaration"] = "Identifier",

  -- Neo-tree
  NeoTreeDimText = "Comment",
  NeoTreeMessage = { fg = c.comment, italic = true },
  NeoTreeFadeText1 = "Comment",
  NeoTreeFadeText2 = "NonText",
  NeoTreeDotfile = "Comment",
  NeoTreeModified = { fg = c.yellow },
  NeoTreeGitConflict = { fg = c.orange, italic = true, bold = true },
  NeoTreeGitModified = { fg = c.soft_orange },
  NeoTreeGitUntracked = { fg = c.soft_orange, italic = true },
  NeoTreeTabActive = "WinBar",
  NeoTreeTabInactive = "TabLine",
  NeoTreeTabSeparatorActive = { fg = c.border, bg = c.bg },
  NeoTreeTabSeparatorInactive = { fg = c.border, bg = c.line },
  NeoTreeFileStats = "Comment",
  NeoTreeFileStatsHeader = { fg = c.comment, bold = true, italic = true },

  -- Neogit
  NeogitHunkHeader = { fg = c.comment, bg = c.line },
  NeogitHunkHeaderHighlight = { fg = c.violet, bg = c.panel },
  NeogitHunkHeaderCursor = "NeogitHunkHeaderHighlight",
  NeogitDiffAddInline = { bg = "#364837" },
  NeogitDiffDeleteInline = { bg = "#57292d" },

  -- Diagnostics and diffs.
  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.blue },
  DiagnosticHint = { fg = c.cyan },
  DiagnosticOk = { fg = c.green },
  DiagnosticDeprecated = { sp = c.red, strikethrough = true },
  DiagnosticUnderlineError = { sp = c.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = c.cyan, undercurl = true },
  DiagnosticUnderlineOk = { sp = c.green, undercurl = true },
  DiffAdd = { bg = "#243126" },
  DiffDelete = { fg = c.red, bg = "#382326" },
  DiffChange = { bg = "#283039" },
  DiffText = { bg = "#354756" },
  Added = { fg = c.green },
  Removed = { fg = c.red },
  Changed = { fg = c.orange },
}

for group, attributes in pairs(groups) do
  vim.api.nvim_set_hl(0, group, type(attributes) == "string" and { link = attributes } or attributes)
end
